package com.spydermama.api.common.changehistory;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonView;
import com.spydermama.api.base.Views;

import io.swagger.annotations.ApiModelProperty;

@Entity(name = "CHANGE_HISTORY")
public class ChangeHistory {

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ChangeHistoryIdGenerator")
	@SequenceGenerator(name = "ChangeHistoryIdGenerator", sequenceName = "SEQ_CHANGE_ID", initialValue = 100, allocationSize = 1)

	@Column(name = "CHANGE_ID")
	@JsonView(value= {Views.Allways.class})
	@ApiModelProperty(value = "Autogenerated nemeric id of the change history entry", position = 1,required=true)
	private Long id;
	@Column(name = "ACTION")
	@Size(max = 20, min=1)
	@JsonView(value= {Views.Allways.class})
	@ApiModelProperty(value = "Action performed on the entity i.e. Add, Update, Delete", position = 2,required=true,example = "Update")
	private String action;
	@Column(name = "ACTION_DATE")
	@JsonView(value= {Views.Allways.class})
	@ApiModelProperty(value = "Date of action", position = 3,required=true)
	private Date date;
	@Column(name = "ACTION_USER")
	@Size(max = 20, min=1)
	@JsonView(value= {Views.Allways.class})
	@ApiModelProperty(value = "User name who performed the action", position = 4,required=true)
	private String user;
	@Column(name = "ENTITY_TYPE")
	@Size(max = 50, min=1)
	@JsonView(value= {Views.Allways.class})
	@ApiModelProperty(value = "Entity/Resource type e.g. Components, Releases etc.", position = 5,required=true)
	private String entityType;
	@Column(name = "ENTITY_NAME")
	@Size(max = 500, min=1)
	@JsonView(value= {Views.Allways.class})
	@ApiModelProperty(value = "Human readable description of the entity/resource", position = 6,required=true)
	private String entityName;
	@Column(name = "ENTITY_ID")
	@Size(max = 100, min=1)
	@JsonView(value= {Views.Allways.class})
	@ApiModelProperty(value = "Id of the entity/resource", position = 7,required=true)
	private String entityId;
	@Column(name = "ACTION_DETAILS")
	@Size(min=0)
	@JsonView(value= {Views.Allways.class})
	@ApiModelProperty(value = "Details of changes made to entity/resource. It is a variable length string stored as CLOB", position = 8)
	private String details;
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getAction() {
		return action;
	}
	public void setAction(String action) {
		this.action = action;
	}
	public Date getDate() {
		return date;
	}
	public void setDate(Date date) {
		this.date = date;
	}
	public String getUser() {
		return user;
	}
	public void setUser(String user) {
		this.user = user;
	}

	public String getEntityType() {
		return entityType;
	}
	public void setEntityType(String entityType) {
		this.entityType = entityType;
	}
	public String getEntityName() {
		return entityName;
	}
	public void setEntityName(String entityName) {
		this.entityName = entityName;
	}
	public String getEntityId() {
		return entityId;
	}
	public void setEntityId(String entityId) {
		this.entityId = entityId;
	}
	public String getDetails() {
		return details;
	}
	public void setDetails(String details) {
		this.details = details;
	}
	
	
}